version: '3.8'
services:
  app:
    build: .
    container_name: nodejs_app
    ports:
      - "5000:5000"  
    env_file:
      - .env 
    depends_on:
      - mongo 
    networks:
      - app-network
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  
    networks:
      - app-network
networks:
  app-network:
    driver: bridge  
